import { defineStore } from 'pinia'
import { container } from 'tsyringe'
import { computed, reactive } from 'vue'
import type { Debt } from '../entities/Debts'
import { DebtFilter} from '../entities/debtFilter'
import { DebtRepository } from '../repositories/DebtRepository'